name: Deploy template to S3 for staging

on:
  workflow_dispatch:
  schedule:
    - cron: "00 10 * * *" # time in UTC

jobs:
  deploy_template:
    strategy:
      matrix:
        include:
          - region: "us-east-2"
            bucket: "acorn-provisioning-cf-us-east-220230411221247894300000001"
          - region: "us-west-2"
            bucket: "acorn-provisioning-cf-us-west-220230413223704926200000001"
          - region: "eu-north-1"
            bucket: "acorn-provisioning-cf-eu-north-120230413223705508800000001"
    name: Deploy template to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS credentials from stg account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_STG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_STG }}
          aws-region: ${{ matrix.region }}
      - name: Copy files to S3
        run: |
          latest=$(ls template | sort -V | tail -1)
          jq '.Parameters.Principal.Default = "${{ secrets.AWS_DEFAULT_PRINCIPAL }}" | .Resources.AcornSetAccountCredentialsLambda.Properties.Code.S3Bucket = "${{ matrix.bucket }}"' template/$latest > template/$latest.processed
          aws s3 cp template/$latest.processed s3://${{ matrix.bucket }}/$latest
